### PR TITLE
Write Matrix stub

### PR DESCRIPTION
**Pull request by bclinthall**
Issue #1 Mostly conforms to style requirements.  Where it diverges, there are good reasons.

### CODE REVIEW

**Review by whereswaldon — APPROVED** [review]
I assume that we're going to fix the remaining style errors when we implement them? If so, I'm fine with this.

**Comment by bclinthall** [comment]
Traditionally and in the specs, matrices are represented by capital letter
variables. The style doesn't allow that. We have to make a choice.

**Comment by whereswaldon** [comment]
I vote that we use lowercase but call them something like `matrixA`. @ccampell, what do you think?

**Comment by campellcl** [comment]
Looks good to me. Which area are we debating capitalization for? I notice we are missing Javadocs for the methods, but if we want to implement them later that's fine with me.

**Comment by whereswaldon** [comment]
We were discussing the capitalization of variables that are Matricies. Whenever a method accepts something of type Matrix, it currently uses a capital letter for it.

**Comment by bclinthall** [comment]
I like Waldon's solution to the capitalization issue.

On Tue, Feb 7, 2017 at 8:14 AM, Christopher Waldon <notifications@github.com

**Pull request merged**
